get http://localhost:3000/users

###
post http://localhost:3000/users
Content-Type: application/json

{
    "name": "Mary Rogers",
    "email": "mary@example.com"
}

###
PUT http://localhost:3000/users/3
Content-Type: application/json

{
    "name": "David Smith",
    "email": "david@example.com"
}

###
DELETE http://localhost:3000/users/5
